#!/bin/sh
# Rebuild corpus/ and golden/golden_pep8.txt from a pinned ansible-lint release.
#
# What this produces is derived from ansible-lint and so is GPL-3.0-or-later,
# which is why it lives here and not in the MIT astl repository.
#
# The golden file is a snapshot of one upstream version. Its pins, toolchain and
# corpus ref, live in scripts/upstream.sh and are shared with
# regenerate-cases.sh: change them there and review the resulting diff.
#
# Usage:
#   scripts/regenerate.sh            # clone into a temporary directory
#   UPSTREAM_SRC=/path/to/clone scripts/regenerate.sh
#
# Requirements: git, python3 (3.10+), pip, network access unless UPSTREAM_SRC is set.
#
# golden/expected_extra.txt is NOT regenerated: it records astl's own known
# divergences and must be reviewed by hand. The script prints how to recompute it.
set -eu

UPSTREAM_URL="${UPSTREAM_URL:-https://github.com/ansible/ansible-lint}"

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

# Shared with regenerate-cases.sh so the two golden files cannot be generated by
# different versions.
. "$ROOT/scripts/upstream.sh"

# 1. Obtain the upstream tree at the pinned ref.
if [ -n "${UPSTREAM_SRC:-}" ]; then
  SRC="$UPSTREAM_SRC"
  echo "using existing clone: $SRC"
else
  SRC="$WORK/ansible-lint"
  echo "cloning $UPSTREAM_URL at $UPSTREAM_REF"
  git clone --depth 1 --branch "$UPSTREAM_REF" "$UPSTREAM_URL" "$SRC"
fi

# 2. Rebuild the corpus. Symlinks are dereferenced (-L) because upstream links
#    examples/playbooks/roles to examples/roles and the golden file carries
#    findings under both paths.
echo "rebuilding corpus/ from $SRC/examples"
rm -rf "$ROOT/corpus"
mkdir -p "$ROOT/corpus"
cp -RL "$SRC/examples/." "$ROOT/corpus/"

# 3. Install the pinned toolchain in a throwaway virtualenv. yamllint and
#    ansible-core are pinned too because they decide golden output; see
#    scripts/upstream.sh.
echo "installing $UPSTREAM_PIP_SPEC"
python3 -m venv "$WORK/venv"
"$WORK/venv/bin/pip" install --quiet --upgrade pip
# shellcheck disable=SC2086  # the spec is three deliberate pip arguments, not one
"$WORK/venv/bin/pip" install --quiet $UPSTREAM_PIP_SPEC

# 4. Run it from the repository root, so reported paths are already relative and
#    rooted at corpus/. --offline keeps galaxy out of the run, --nocolor keeps
#    ANSI escapes out of the golden file.
#
#    Two environment settings are neutralized because they change the output.
#    The yamllint variables decide which yaml findings appear; XDG_CONFIG_HOME
#    points at an empty directory rather than being unset, because unsetting it
#    falls back to ~/.config. ANSIBLE_HOME decides which modules resolve, and
#    risky-file-permissions only reports on the ones it recognises: a machine
#    carrying community.general sees 14 findings where bare ansible-core sees 3,
#    and --offline does not hide collections already on disk.
echo "running ansible-lint over corpus/"
cd "$ROOT"
unset YAMLLINT_CONFIG_FILE
XDG_CONFIG_HOME="$WORK/xdg"
ANSIBLE_HOME="$WORK/ansible"
export XDG_CONFIG_HOME ANSIBLE_HOME
"$WORK/venv/bin/ansible-lint" --offline --nocolor -f pep8 corpus > "$WORK/raw.txt" || true

# 5. Keep only the rules astl implements. The list is shared with the other
#    regeneration script so the two goldens cannot be filtered differently.
. "$ROOT/scripts/rules.sh"

grep -E "^[^ ]+:[0-9]+(:[0-9]+)?: ($RULES)(\[|:)" "$WORK/raw.txt" > "$WORK/filtered.txt"

# 6. Normalize paths to the corpus/ prefix, then sort. Step 4 already emits
#    relative paths, so the sed only strips an absolute prefix if a future
#    ansible-lint reports one.
#
#    The sort is what makes this byte-reproducible: ansible-lint's output order
#    is not stable across runs and the harness compares sorted lines anyway
#    (check_test.go:sortedLines), so without it a regeneration that changed
#    nothing still produces a large diff, which is where a real change hides.
#    LC_ALL=C because the default collation is another machine property, and it
#    matches Go's byte-wise sort.Strings on the comparing side.
sed -e "s#^$ROOT/##" -e 's#^\./##' "$WORK/filtered.txt" \
  | LC_ALL=C sort > "$ROOT/golden/golden_pep8.txt"

echo "golden lines: $(wc -l < "$ROOT/golden/golden_pep8.txt")"
cat <<'EOF'

corpus/ and golden/golden_pep8.txt are regenerated.

golden/expected_extra.txt was NOT touched. Recompute the candidate set with a
checkout of github.com/arhuman/ansible-static-lint:

  (cd ../ansible-static-lint && go build -o /tmp/astl ./cmd/astl)
  /tmp/astl corpus | sort > /tmp/astl-out.txt
  sort golden/golden_pep8.txt > /tmp/golden-sorted.txt
  comm -23 /tmp/astl-out.txt /tmp/golden-sorted.txt

Review every line of that output, explain each one in PARITY.md, and only then
write it to golden/expected_extra.txt. An unreviewed extra is a false positive
shipped as a contract.
EOF
