#!/bin/sh
# The pinned upstream toolchain the golden files are generated with.
#
# Sourced by every script that installs or checks that toolchain, so the corpus
# contract and the cases contract cannot be generated by different versions.
#
# All three pins decide the output: ansible-lint owns most of the rules, yamllint
# decides every yaml finding, and ansible-core resolves the modules behind the
# fqcn and syntax checks. Installing only ansible-lint lets pip pick the other
# two, so a regeneration a year from now would compare against a different policy.
#
# Changing any of these changes the contract: change it here, regenerate both
# golden files, review the diff.
#
# Still unpinned, and so free to move under a regeneration: ansible-compat and
# ruamel-yaml, the parser behind the yaml rules. `ansible-lint --version` prints
# both if a future drift needs tracing.

UPSTREAM_VERSION="${UPSTREAM_VERSION:-26.8.0}"
YAMLLINT_VERSION="${YAMLLINT_VERSION:-1.38.0}"
ANSIBLE_CORE_VERSION="${ANSIBLE_CORE_VERSION:-2.21.3}"

# Tag or commit the corpus tree is taken from. Kept beside UPSTREAM_VERSION
# because the two describe one upstream release and must move together.
UPSTREAM_REF="${UPSTREAM_REF:-v26.8.0}"

# The pip specifier every installer uses, so the three pins cannot be applied in
# one script and forgotten in another.
# shellcheck disable=SC2034  # consumed by the scripts that source this file
UPSTREAM_PIP_SPEC="ansible-lint==$UPSTREAM_VERSION yamllint==$YAMLLINT_VERSION ansible-core==$ANSIBLE_CORE_VERSION"
